baseURL = "https://adamcrowder.net"
title = "Adam Crowder"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlangauge = "en"
enableRobotsTXT = true

paginate = 20
canonifyurls = true

pygmentsstyle = "native"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Adam Crowder"
    info = "Back-end software engineer. Specializations in cloud services, blockchains, and networking, with interests in cryptography and secure protocols."
    description = "Adam Crowder's personal website and blog"
    keywords = "blog,developer,personal,project,programming"
    avatarurl = "images/headshot.jpg"
    favicon_32 = "images/favicon-32.png"
    favicon_16 = "images/favicon-16.png"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideFooter = false
    hidecredits = true
    hidecopyright = true

    rtl = false

    colorscheme = "dark"
    hidecolorschemetoggle = false

    maxSeeAlsoItems = 5

    enableTwemoji = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/cheeseandcereal/"
# [[params.social]]
#     name = "LinkedIn"
#     icon = "fa fa-linkedin"
#     weight = 2
#     url = "https://www.linkedin.com/in/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/posts/"
# [[menu.main]]
#     name = "Projects"
#     weight = 3
#     url = "/projects/"
[[menu.main]]
    name = "Contact me"
    weight = 4
    url = "/contact/"
