baseURL = "https://adamcrowder.net/"
title = "Adam Crowder"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlangauge = "en"
enableRobotsTXT = true

pygmentsstyle = "native"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Adam Crowder"
    info = "Backend software engineer. Specializations in blockchains, distributed systems, cloud services, networking, cryptography, and secure protocols."
    description = "Adam Crowder's personal website and blog"
    keywords = "blog,developer,personal,project,programming"
    avatarurl = "images/avatar.jpg"
    favicon_32 = "images/favicon-32.png"
    favicon_16 = "images/favicon-16.png"

    hidecredits = true
    hidecopyright = true
    rtl = false

    inverted = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/cheeseandcereal/"
# [[params.social]]
#     name = "LinkedIn"
#     icon = "fab fa-linkedin fa-2x"
#     weight = 2
#     url = "https://www.linkedin.com/in/"

# Menu links
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url = "/posts/"
# [[menu.main]]
#     name = "Projects"
#     weight = 3
#     url = "/projects/"
[[menu.main]]
    name = "Contact me"
    weight = 4
    url = "/contact/"
